route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: remoTE
receivers:
- name: remoTE
  webhook_configs:
   - http_config:
       basic_auth:
          username: User
          password: User
     url: 'URL_FOR_WEBHOOK'
     send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
