{
 "title": "Cassandra Dashboard",
 "tags": [
  "cassandra",
  "salt",
  "java",
  "cortex"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count, cluster)"
    }
   },
   {
    "name": "datacenter",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{cluster=\"$cluster\"}, datacenter)"
    }
   },
   {
    "name": "keyspace",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\"}, keyspace)"
    }
   },
   {
    "name": "table",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\"}, table)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\",}, instance)"
    }
   },
   { "name": "interval", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_load_count{cluster=\"$cluster\", datacenter=\"$datacenter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=\"prod_cassandra_monitor\", datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cassandra_client_connectednativeclients{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Availabilty",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (sum by (instance) (irate(jvm_gc_collection_seconds_sum{cluster=\"$cluster\", datacenter=\"$datacenter\", instance=~\"$instance\",}[3m])))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "GC Count / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_collection_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m])",
       "legendFormat": "{{ instance }} - {{ gc }}"
      }
     ]
    },
    {
     "title": "Avg GC Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_collection_seconds_sum{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) / irate(jvm_gc_collection_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m])",
       "legendFormat": "{{ instance }} - {{ gc }}"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "jvm_memory_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - committed"
      },
      {
       "expr": "jvm_memory_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - used"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "jvm_memory_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - committed"
      },
      {
       "expr": "jvm_memory_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - used"
      }
     ]
    },
    {
     "title": "Heap Used (Old Gen)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - used - {{ pool }}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_peak{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - peak"
      },
      {
       "expr": "jvm_threads_daemon{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - daemon"
      },
      {
       "expr": "jvm_threads_current{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - current"
      },
      {
       "expr": "jvm_threads_deadlocked{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - deadlocked"
      }
     ]
    },
    {
     "title": "Direct Buffer Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_pool_capacity_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"direct\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - capacity"
      },
      {
       "expr": "jvm_buffer_pool_used_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"direct\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - used"
      }
     ]
    },
    {
     "title": "Mapped Buffer Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_pool_capacity_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"mapped\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - capacity"
      },
      {
       "expr": "jvm_buffer_pool_used_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"mapped\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - used"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{job=\"prod_cassandra_monitor\", datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "process_open_fds{job=\"cassandra\", datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - open"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM MEMORY DETAIL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap - Eden",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "NonHeap - Metaspace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "Heap - Survivor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "NonHeap - Code Cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "Heap - Old",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "NonHeap - Compressed Class Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CLUSTER - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_keyspace_readlatency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", instance=~\"$instance\"}[3m])) > 0",
       "legendFormat": "reads"
      }
     ]
    },
    {
     "title": "Writes / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_keyspace_writelatency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Connection Timeouts / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (connection) (irate(cassandra_connection_timeouts_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "dst {{ connection }}"
      }
     ]
    },
    {
     "title": "Client Timeouts And Failures / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_clientrequest_timeouts_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "timeout"
      },
      {
       "expr": "sum(irate(cassandra_clientrequest_failures_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_keyspace_totaldiskspaceused{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Disk Used by instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (cassandra_keyspace_totaldiskspaceused{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - used"
      }
     ]
    },
    {
     "title": "Compaction / 2m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cassandra_compaction_bytescompacted_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[2m]))"
      }
     ]
    },
    {
     "title": "Hints Service  / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_hintsservice_hintsfailed_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(irate(cassandra_hintsservice_hintstimedout_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "timeout"
      },
      {
       "expr": "sum(irate(cassandra_hintsservice_hintssucceeded_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "succeeded"
      }
     ]
    },
    {
     "title": "Dropped Messages / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (droppedmessage) (irate(cassandra_droppedmessage_dropped_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "{{ droppedmessage }}"
      }
     ]
    },
    {
     "title": "Compaction Tasks / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_compaction_completedtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "completed"
      },
      {
       "expr": "sum(irate(cassandra_compaction_pendingtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Prepared Statements Ratio",
     "type": "graph",
     "description": "Percentage of statements that are prepared vs unprepared.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_cql_preparedstatementsratio{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "CAS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_keyspace_cascommitlatency_seconds_count{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\"}[3m]))",
       "legendFormat": "CAS commit"
      },
      {
       "expr": "sum(irate(cassandra_keyspace_caspreparelatency_seconds_count{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\"}[3m]))",
       "legendFormat": "CAS prepare"
      },
      {
       "expr": "sum(irate(cassandra_keyspace_casproposelatency_seconds_count{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\"}[3m]))",
       "legendFormat": "CAS propose"
      }
     ]
    },
    {
     "title": "Thread Pools Active Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster, path, threadpools) (cassandra_threadpools_activetasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{ path }}: {{ threadpools }}"
      }
     ]
    },
    {
     "title": "Thread Pools Completed Tasks / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster, path, threadpools) (irate(cassandra_threadpools_completedtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "{{ path }}: {{ threadpools }}"
      }
     ]
    },
    {
     "title": "Thread Pools Pending Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster, path, threadpools) (cassandra_threadpools_pendingtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{ path }}: {{ threadpools }}"
      }
     ]
    },
    {
     "title": "Threadpools Max Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_threadpools_maxpoolsize{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ path }} {{ threadpools }}"
      }
     ]
    },
    {
     "title": "Threadpools Total Blocked Tasks / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster, path, threadpools) (irate(cassandra_threadpools_totalblockedtasks_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "{{ path }} {{ threadpools }}"
      }
     ]
    },
    {
     "title": "Cache Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (cache) (cassandra_cache_capacity{cluster=\"$cluster\", datacenter=\"$datacenter\", instance=~\"$instance\"})",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Col Update Time Delta",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_keyspace_colupdatetimedeltahistogram{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\", quantile=\"0.50\", instance=~\"$instance\"})",
       "legendFormat": "50 percentile"
      },
      {
       "expr": "avg(cassandra_keyspace_colupdatetimedeltahistogram{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\", quantile=\"0.99\", instance=~\"$instance\"})",
       "legendFormat": "99 percentile"
      }
     ]
    },
    {
     "title": "The number of SSTables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cluster_datacenter_instance_keyspace:cassandra_table_livesstablecount:sum{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CLIENT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster, clientrequest) (irate(cassandra_clientrequest_latency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", clientrequest!~\"Read|.*Write.*\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "{{ clientrequest }} "
      }
     ]
    },
    {
     "title": "Writes / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster, clientrequest) (irate(cassandra_clientrequest_latency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", clientrequest!~\"Write|.*Read.*|RangeSlice\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "{{ clientrequest }}"
      }
     ]
    },
    {
     "title": "Client Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", quantile=\"0.99\", clientrequest=~\".*Read.*\", instance=~\"$instance\"})",
       "legendFormat": "99p"
      },
      {
       "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", quantile=\"0.95\", clientrequest=~\".*Read.*\", instance=~\"$instance\"})",
       "legendFormat": "95p"
      },
      {
       "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", quantile=\"0.75\", clientrequest=~\".*Read.*\", instance=~\"$instance\"})",
       "legendFormat": "75p"
      }
     ]
    },
    {
     "title": "Client Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", quantile=\"0.99\", clientrequest=~\".*Write.*\"})",
       "legendFormat": "99p"
      },
      {
       "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", quantile=\"0.95\", clientrequest=~\".*Write.*\"})",
       "legendFormat": "95p"
      },
      {
       "expr": "max by (cluster) (cassandra_clientrequest_latency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", quantile=\"0.75\", clientrequest=~\".*Write.*\"})",
       "legendFormat": "75p"
      }
     ]
    },
    {
     "title": "Client Timeouts and Failures / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (irate(cassandra_clientrequest_timeouts_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "timeout"
      },
      {
       "expr": "sum by (cluster) (irate(cassandra_clientrequest_failures_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Client Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_client_connectednativeclients{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - native"
      },
      {
       "expr": "cassandra_client_connectedthriftclients{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - thrift"
      }
     ]
    },
    {
     "title": "Client Authorizations / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cluster) (irate(cassandra_client_authsuccess_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (cluster) (irate(cassandra_client_authfailure_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]))",
       "legendFormat": "failure"
      }
     ]
    }
   ]
  },
  {
   "title": "MEMTABLE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memtable Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (cassandra_table_allmemtablesheapsize{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - heap"
      },
      {
       "expr": "sum by (instance) (cassandra_table_allmemtablesoffheapsize{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - off_heap"
      }
     ]
    },
    {
     "title": "Memtable Switch Count / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_memtableswitchcount{cluster=\"$cluster\", datacenter=\"$datacenter\", instance=~\"$instance\"}[3m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Waiting on free memtable space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (cassandra_table_waitingonfreememtablespace{cluster=\"$cluster\", datacenter=\"$datacenter\", quantile=\"0.50\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - 50 percentile"
      },
      {
       "expr": "sum by (instance) (cassandra_table_waitingonfreememtablespace{cluster=\"$cluster\", datacenter=\"$datacenter\", quantile=\"0.99\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - 99 percentile"
      }
     ]
    },
    {
     "title": "Bloomfilter disk space used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_keyspace_bloomfilterdiskspaceused{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - used"
      }
     ]
    },
    {
     "title": "Flushed / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_bytesflushed{cluster=\"$cluster\", datacenter=\"$datacenter\", instance=~\"$instance\"}[3m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  { "title": "TABLE - $table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Reads / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (irate(cassandra_table_readlatency_seconds_count{cluster=\"$cluster\", datacenter=\"$datacenter\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Writes / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (irate(cassandra_table_writelatency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_readlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency (95%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_writelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.95\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_readlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.99\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_writelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.99\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Coordinator Read Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_coordinatorreadlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}))",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Coordinator Scan Latency (99%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (table) (cassandra_table_coordinatorscanlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}))",
     "legendFormat": "{{ instance }} - {{ table }}"
    }
   ]
  },
  {
   "title": "Dropped Mutations / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (cluster, table) (irate(cassandra_table_droppedmutations_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Compaction Bytes Written / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (irate(cassandra_table_compactionbyteswritten_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m])))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Tombstones Scanned In Queries (99%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (table) (cassandra_table_tombstonescannedhistogram{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Disk Used Top 10",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (table) (cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\"}))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "TABLE TOP 10 by instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "topk(10, irate(cassandra_table_readlatency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m]) * 60)",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "wpm" }
     ],
     "targets": [
      {
       "expr": "topk(10, irate(cassandra_table_writelatency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m]) * 60)",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Read Latency (95%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_readlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Write Latency (95%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_writelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Read Latency (99.9%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_readlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Write Latency (99.9%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_writelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Coordinator Read Latency (99.9%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_coordinatorreadlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Coordinator Write Latency (99.9%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_coordinatorwritelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Coordinator Scan Latency (99.9%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_coordinatorscanlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Compaction Bytes Written",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_compactionbyteswritten_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} - cassandra_table_compactionbyteswritten_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} offset 1m)",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Tombstones Scanned In Queries (99.9%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_tombstonescannedhistogram{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.999\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Dropped Mutations For 1 Minute",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "topk(10, (cassandra_table_droppedmutations_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} - cassandra_table_droppedmutations_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} offset 1m))",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Total Disk Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (instance) (cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk Used Per Table",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"})",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    }
   ]
  }
 ]
}